language: rust
rust:
  - nightly-2018-12-15
  
addons:
  apt:
    packages: binutils-dev libcurl4-openssl-dev zlib1g-dev libdw-dev libiberty-dev make
before_install:
    - |
        if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
            wget https://www.nasm.us/pub/nasm/releasebuilds/2.13.03/nasm-2.13.03.tar.xz
            tar -xvf nasm-2.13.03.tar.xz
            cd nasm-2.13.03
            ./configure
            make
            sudo make install
            cd ..
            nasm --version
        fi
jobs:
  include:
      - name: "Makefile build (Linux)"
        script: make examples && ./simple_encoding
      - name: "Makefile build (macOS)"
        os: osx
        script: make examples && ./simple_encoding
      - name: "Cargo build"
        script: cargo build --verbose
      - name: "Cargo test"
        script: cargo test --verbose
