[package]
name = "crav1e"
version = "0.1.0"
authors = ["Luca Barbato <lu_zero@gentoo.org>"]

[lib]
name = "rav1e"
crate-type = ["cdylib"]

[build-dependencies]
cbindgen = "0.6.3"

[dependencies.rav1e]
git = "https://github.com/xiph/rav1e"
