[package]
name = "dummy"
version = "0.1.0"
authors = ["lu_zero <lu_zero@gentoo.org>"]
edition = "2018"

[lib]
crate-type = ["staticlib"]

[dependencies.rav1e]
git = "https://github.com/xiph/rav1e"
default-features = false
